#!/bin/bash
echo "hello welcome to kingterm system installer" |lolcat
echo "want to download the system in which directory?" |lolcat
read directory_download_system
echo "what is your name"|lolcat
read name_first
echo "how old are you?"|lolcat
read age_first
echo "pre install app on system?"|lolcat
read pre_install_app
if [ $pre_install_app == "y" ];then
  echo "which?" |lolcat
  read pre_yes_install
fi

figlet load...|lolcat
git clone https://github.com/edumast/termking
sed -i "s/name_usr=.*#end/name_usr=$name_first #end/g" ~/$directory_download_system/update/termking/databased/database
sed -i "s/age_usr=.*#end/age_usr=$age_first #end/g" ~/$directory_download_system/update/termking/databased/database
sed -i "s/app1=.*#end/app1=$pre_yes_install #end/g" ~/$directory_download_system/update/termking/databased/database

   mv ~/$directory_download_system/update/termking/update/* ~/$directory_download_system/update
   mv ~/$directory_download_system/update/termking/* ~/$directory_download_system
   rm -rf termking
   echo done |lolcat

