#!/bin/bash
directory=`echo $PWD | rev | cut -d'/' -f 2 | rev`
echo "continue?"
read s_or_n_continue
if [ $s_or_n_continue == "dc" ];then
  echo "qual o diretorio atual?"
  read directory
elif [ $s_or_n_continue == "n" ];then
  exit
else
  directory="term"
fi
git clone https://github.com/edumast/termking 
mv ~/$directory/termking/* ~/$directory
sleep 1
rm -rf termking
